### ISSUE TITLE
Advanced & Practical Enum usage in Swift: Tuples as Arguments

### ISSUE THREAD

**Issue by mathonsunday** [terhechte/appventure-blog#17]
In this code example:

```swift
typealias Config = (RAM: Int, CPU: String, GPU: String)

// Each of these takes a config and returns an updated config
func selectRAM(_ config: Config) -> Config {return (RAM: 32, CPU: config.CPU, GPU: config.GPU)}
func selectCPU(_ config: Config) -> Config {return (RAM: config.RAM, CPU: "3.2GHZ", GPU: config.GPU)}
func selectGPU(_ config: Config) -> Config {return (RAM: config.RAM, CPU: "3.2GHZ", GPU: "NVidia")}

enum Desktop {
   case Cube(Config)
   case Tower(Config)
   case Rack(Config)
}

let aTower = Desktop.Tower(selectGPU(selectCPU(selectRAM((0, "", "") as Config))))
```

Why do the select functions (selectRAM, selectCPU, selectGPU) set the value of the associated values? It would make more sense if the functions took in the new value and the config and then set the new value based on the input.

Also, I'm not clear on what "select" means here. The word "set" or "update" make more sense to me based on my understanding of these functions.

**Comment by terhechte** [comment]
You're right. I was trying to find a very short example for the ability of Swift to chain a tuple through a series of commands where each command adds something to the tuple. The idea was, that the `select*` func would select a particular entry (say a 3.2GHZ CPU) from a set of different options. However, in order to keep the example small, I shortened it multiple times, until the original names (select*) were not compatible anymore; set* would have been a better name indeed. That also explains why they're not setting the value as an input (i.e. ```func setCPU(_ config: Config, selectedCPU: String) -> Config```):
 
Because I initially envisioned the selection to come from a database or some other shared, global, state, to keep the example short.

**Comment by mathonsunday** [comment]
Thanks for the explanation!

**Comment by terhechte** [comment]
You're welcome :)
